name: phish-base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - opencv-python==3.4.2.17
    - opencv-contrib-python==3.4.2.17
    - tensorflow==1.13.1
    - ipykernel==5.5.6
    - pandas
    - tldextract
    - bs4
    - tqdm
    - scikit-learn==0.21.3
    - sklearn
    - h5py
    - xgboost==0.90
